### ISSUE TITLE
Waymo example: Render 3D does not work

### ISSUE THREAD

**Issue by abastola0** [metadriverse/scenarionet#55]
I followed the documentation for running the waymo example. The 2D rendering works with --render 2D but I'm getting errors in --render 3D with these lines:

python -m scenarionet.sim -d /path/to/exp_converted/ --render 3D 

and python -m scenarionet.sim -d /path/to/exp_converted/ --render advanced

I'm getting this error: 

Traceback (most recent call last):
  File "/home/abastol/modules/anaconda3/envs/sim/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/abastol/modules/anaconda3/envs/sim/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/abastol/working/visionIRL/scenarionet/scenarionet/sim.py", line 52, in <module>
    env.reset(seed=index if args.scenario_index is None else args.scenario_index)
  File "/home/abastol/working/visionIRL/metadrive/metadrive/envs/base_env.py", line 531, in reset
    reset_info = self.engine.reset()
  File "/home/abastol/working/visionIRL/metadrive/metadrive/engine/base_engine.py", line 377, in reset
    self.terrain.reset(center_p)
  File "/home/abastol/working/visionIRL/metadrive/metadrive/engine/core/terrain.py", line 141, in reset
    semantics = self.get_terrain_semantics(center_point)
  File "/home/abastol/working/visionIRL/metadrive/metadrive/engine/core/terrain.py", line 591, in get_terrain_semantics
    semantics = self.engine.current_map.get_semantic_map(
  File "/home/abastol/working/visionIRL/metadrive/metadrive/component/map/base_map.py", line 256, in get_semantic_map
    points = [
  File "/home/abastol/working/visionIRL/metadrive/metadrive/component/map/base_map.py", line 260, in <listcomp>
    ] for x, y in polygon
ValueError: too many values to unpack (expected 2)

I also tried the advanced version with Panda3D rendering but that also does not work. I tested the Pandas3D independently and it just works fine. The metadrive simulator also works fine.

**Comment by QuanyiLi** [comment]
Could you pull the latest MetaDrive and try again? I merged a PR for fixing this

**Comment by abastola0** [comment]
Yeah it works now. Thanks.

**Comment by zhexilian** [comment]
Hi Mr.Li:
I think this problem still exists under windows. My collegue pull the 4.2.3 Metadrive under Ubuntu and it worked. But I pull the 4.2.3 Metadrive under windows and failed. The error is " ValueError: too many values to unpack (expected 2)"
